In [72]:
import emoji

In [73]:
print(emoji.emojize(':thumbs_up:'))

üëç


In [74]:
print(emoji.demojize('üòç'))

:smiling_face_with_heart-eyes:


In [75]:
print(emoji.emojize(':flight:'))

:flight:


In [76]:
import pandas as pd

In [77]:
df = pd.read_csv('emoji_data.csv', header = None)

In [78]:
df.head(2)

0  1
0  French macaroon is so tasty  4
1             work is horrible  3

In [79]:
df.describe()

0    1
count             183  183
unique            181   11
top     I want to eat    2
freq                2   55

In [80]:
df.head(12)

0   1
0           French macaroon is so tasty   4
1                      work is horrible   3
2                            I am upset  3 
3                        throw the ball  1 
4                             Good joke   2
5   what is your favorite baseball game   1
6                         I cooked meat   4
7                   stop messing around   3
8                   I want chinese food   4
9               Let us go play baseball   1
10        you are failing this exercise   3
11              yesterday we lost again  3

In [121]:
emoj = {
    0: ":red_heart:",
    1: ":cricket_game:",
    2: ":beaming_face_with_smiling_:",
    3: ":pensive_face:",
    4: ":face_savoring_food:"
}

def to_emoji(label):
    return emoji.emojize(emoj[label])

In [125]:
to_emoji(2)

':beaming_face_with_smiling_:'

In [82]:
x = df[0].values

In [83]:
x

array(['French macaroon is so tasty', 'work is horrible', 'I am upset',
       'throw the ball', 'Good joke',
       'what is your favorite baseball game', 'I cooked meat',
       'stop messing around', 'I want chinese food',
       'Let us go play baseball', 'you are failing this exercise',
       'yesterday we lost again', 'Good job', 'ha ha ha it was so funny',
       'I will have a cheese cake', 'Why are you feeling bad',
       'I want to joke', 'I never said yes for this',
       'the party is cancelled', 'where is the ball', 'I am frustrated',
       'ha ha ha lol', 'she said yes', 'he got a raise',
       'family is all I have', 'he can pitch really well',
       'I love to the stars and back', 'do you like pizza ',
       'You totally deserve this prize', 'I miss you so much',
       'I like your jacket ', 'she got me a present',
       'will you be my valentine', 'you failed the midterm',
       'Who is down for a restaurant', 'valentine day is near',
       'Great so awesome

In [85]:
y = df[1].values
y

array(['4', '3', '3 ', '1 ', '2', '1', '4', '3', '4', '1', '3', '3 ', '2',
       '2', '4', '3', '2', '3 ', '3 ', '1', '3 ', '2', '2', '2', '0', '1',
       '0', '4 ', '2', '0v2', '2', '0', '0', '3 ', '4', '0', '2', '1',
       '3', '1', '0', '4', '0 ', '3', '0 ', '4', '2', '3 ', '4', '2 ',
       '2', '3', '0', '2', '2', '3 ', '2', '3', '2', '2', '3 ', '3', '0 ',
       '2', '3', '0', '2', '0', '0 ', '2', '3', '2', '4', '1', '3', '3',
       '0', '0', '3', '2', '0', '3', '0', '2', '2', '4', '2', '2', '0',
       '0', '2', '3', '0', '4', '2', '1', '2', '3', '3', '2', '3', '0',
       '3', '0', '2', '0', '2', '3', '4', '3', '1', '3', '4', '3', '2',
       '3', '3', '3', '1', '4', '4', '2', '2', '1', '1', '2', '3', '2',
       '3', '4', '2', '3', '0', '2', '0', '0', '4', '3', '4', '2', '3',
       '2', '3', '4', '2', '1', '2', '4', '3', '1', '3', '2', '3', '2',
       '2', '3', '3', '2', '4', '0', '0', '0', '3', '0', '0', '1', '1',
       '2', '2', '2', '0', '3', '2', '3', '3', '1', '2',

In [87]:
y = ['4', '3', '3 ', '1 ', '2', '1', '4', '3', '4', '1', '3', '3 ', '2',
       '2', '4', '3', '2', '3 ', '3 ', '1', '3 ', '2', '2', '2', '0', '1',
       '0', '4 ', '2', '0', '2', '0', '0', '3 ', '4', '0', '2', '1',
       '3', '1', '0', '4', '0 ', '3', '0 ', '4', '2', '3 ', '4', '2 ',
       '2', '3', '0', '2', '2', '3 ', '2', '3', '2', '2', '3 ', '3', '0 ',
       '2', '3', '0', '2', '0', '0 ', '2', '3', '2', '4', '1', '3', '3',
       '0', '0', '3', '2', '0', '3', '0', '2', '2', '4', '2', '2', '0',
       '0', '2', '3', '0', '4', '2', '1', '2', '3', '3', '2', '3', '0',
       '3', '0', '2', '0', '2', '3', '4', '3', '1', '3', '4', '3', '2',
       '3', '3', '3', '1', '4', '4', '2', '2', '1', '1', '2', '3', '2',
       '3', '4', '2', '3', '0', '2', '0', '0', '4', '3', '4', '2', '3',
       '2', '3', '4', '2', '1', '2', '4', '3', '1', '3', '2', '3', '2',
       '2', '3', '3', '2', '4', '0', '0', '0', '3', '0', '0', '1', '1',
       '2', '2', '2', '0', '3', '2', '3', '3', '1', '2', '2', '4', '2',
       '3', '1', '2']

In [88]:
y

['4',
 '3',
 '3 ',
 '1 ',
 '2',
 '1',
 '4',
 '3',
 '4',
 '1',
 '3',
 '3 ',
 '2',
 '2',
 '4',
 '3',
 '2',
 '3 ',
 '3 ',
 '1',
 '3 ',
 '2',
 '2',
 '2',
 '0',
 '1',
 '0',
 '4 ',
 '2',
 '0',
 '2',
 '0',
 '0',
 '3 ',
 '4',
 '0',
 '2',
 '1',
 '3',
 '1',
 '0',
 '4',
 '0 ',
 '3',
 '0 ',
 '4',
 '2',
 '3 ',
 '4',
 '2 ',
 '2',
 '3',
 '0',
 '2',
 '2',
 '3 ',
 '2',
 '3',
 '2',
 '2',
 '3 ',
 '3',
 '0 ',
 '2',
 '3',
 '0',
 '2',
 '0',
 '0 ',
 '2',
 '3',
 '2',
 '4',
 '1',
 '3',
 '3',
 '0',
 '0',
 '3',
 '2',
 '0',
 '3',
 '0',
 '2',
 '2',
 '4',
 '2',
 '2',
 '0',
 '0',
 '2',
 '3',
 '0',
 '4',
 '2',
 '1',
 '2',
 '3',
 '3',
 '2',
 '3',
 '0',
 '3',
 '0',
 '2',
 '0',
 '2',
 '3',
 '4',
 '3',
 '1',
 '3',
 '4',
 '3',
 '2',
 '3',
 '3',
 '3',
 '1',
 '4',
 '4',
 '2',
 '2',
 '1',
 '1',
 '2',
 '3',
 '2',
 '3',
 '4',
 '2',
 '3',
 '0',
 '2',
 '0',
 '0',
 '4',
 '3',
 '4',
 '2',
 '3',
 '2',
 '3',
 '4',
 '2',
 '1',
 '2',
 '4',
 '3',
 '1',
 '3',
 '2',
 '3',
 '2',
 '2',
 '3',
 '3',
 '2',
 '4',
 '0',
 '0',
 '0',
 '3',
 '0',


In [89]:
f = open('glove.6B.100d.txt', 'r', encoding='utf8')
c = f.readlines()
f.close()

In [90]:
embedding = {}
embedding

{}

In [91]:
import numpy as np
for line in c:
    line = line.split()
    embedding[line[0]] = np.array(line[1:], dtype = float)

In [92]:
embedding

{'the': array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
        -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
         0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
        -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
         0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
        -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
         0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
         0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
        -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
        -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
        -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
        -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
        -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
        -1.2526  ,  0.071624,  

In [93]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [94]:
tokenizer = Tokenizer()

In [95]:
tokenizer.fit_on_texts(x)

In [96]:
w2i = tokenizer.word_index
len(w2i)

312

In [97]:
w2i

{'i': 1,
 'you': 2,
 'is': 3,
 'the': 4,
 'a': 5,
 'so': 6,
 'am': 7,
 'my': 8,
 'to': 9,
 'this': 10,
 'are': 11,
 'ha': 12,
 'for': 13,
 'she': 14,
 'he': 15,
 'me': 16,
 'not': 17,
 'love': 18,
 'your': 19,
 'want': 20,
 'have': 21,
 'it': 22,
 'got': 23,
 'like': 24,
 'did': 25,
 'baseball': 26,
 'food': 27,
 'was': 28,
 'do': 29,
 'joke': 30,
 'stop': 31,
 'will': 32,
 'miss': 33,
 'life': 34,
 'ball': 35,
 'good': 36,
 'what': 37,
 'go': 38,
 'job': 39,
 'funny': 40,
 'bad': 41,
 'day': 42,
 'great': 43,
 'dinner': 44,
 'that': 45,
 'with': 46,
 'at': 47,
 'of': 48,
 'game': 49,
 'we': 50,
 'again': 51,
 'said': 52,
 'yes': 53,
 'lol': 54,
 'and': 55,
 'down': 56,
 'had': 57,
 'her': 58,
 'fun': 59,
 'smile': 60,
 'lot': 61,
 'working': 62,
 'him': 63,
 'cute': 64,
 'on': 65,
 'lets': 66,
 'messing': 67,
 'us': 68,
 'play': 69,
 'exercise': 70,
 'lost': 71,
 'never': 72,
 'where': 73,
 'can': 74,
 'well': 75,
 'much': 76,
 'valentine': 77,
 'restaurant': 78,
 'awesome': 79,
 'lik

In [98]:
xtokens = tokenizer.texts_to_sequences(x)
x[5]

'what is your favorite baseball game'

In [99]:
xtokens

[[103, 104, 3, 6, 105],
 [106, 3, 107],
 [1, 7, 108],
 [109, 4, 35],
 [36, 30],
 [37, 3, 19, 110, 26, 49],
 [1, 111, 112],
 [31, 67, 113],
 [1, 20, 114, 27],
 [115, 68, 38, 69, 26],
 [2, 11, 116, 10, 70],
 [117, 50, 71, 51],
 [36, 39],
 [12, 12, 12, 22, 28, 6, 40],
 [1, 32, 21, 5, 118, 119],
 [120, 11, 2, 121, 41],
 [1, 20, 9, 30],
 [1, 72, 52, 53, 13, 10],
 [4, 122, 3, 123],
 [73, 3, 4, 35],
 [1, 7, 124],
 [12, 12, 12, 54],
 [14, 52, 53],
 [15, 23, 5, 125],
 [126, 3, 127, 1, 21],
 [15, 74, 128, 129, 75],
 [1, 18, 9, 4, 130, 55, 131],
 [29, 2, 24, 132],
 [2, 133, 134, 10, 135],
 [1, 33, 2, 6, 76],
 [1, 24, 19, 136],
 [14, 23, 16, 5, 137],
 [32, 2, 138, 8, 77],
 [2, 139, 4, 140],
 [141, 3, 56, 13, 5, 78],
 [77, 42, 3, 142],
 [43, 6, 79],
 [29, 2, 21, 5, 35],
 [15, 74, 17, 29, 143],
 [15, 80, 26],
 [50, 57, 81, 5, 144, 44, 145],
 [146, 11, 147],
 [15, 3, 5, 36, 148],
 [72, 149, 9, 16, 51],
 [1, 33, 58],
 [27, 3, 34],
 [1, 7, 150, 59],
 [6, 41, 45, 2, 151, 152, 46, 68],
 [29, 2, 20, 9, 15

In [100]:
def get_max(df):
    max_len = 0
    for sent in df:
        max_len = max(max_len, len(sent))
    return max_len

In [101]:
max_len = get_max(xtokens)

In [102]:
max_len

10

In [103]:
xtrain = pad_sequences(xtokens, maxlen = max_len, padding = 'post')
xtokens[:3]

[[103, 104, 3, 6, 105], [106, 3, 107], [1, 7, 108]]

In [104]:
xtrain[:3]

array([[103, 104,   3,   6, 105,   0,   0,   0,   0,   0],
       [106,   3, 107,   0,   0,   0,   0,   0,   0,   0],
       [  1,   7, 108,   0,   0,   0,   0,   0,   0,   0]])

In [105]:
embed_s = 100
e_matrix = np.zeros((len(w2i)+1, embed_s))

In [106]:
e_matrix[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
for word,a in w2i.items():
    e_vector = embedding[word]
    e_matrix[a] = e_vector

In [108]:
e_matrix

array([[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [-0.046539,  0.61966 ,  0.56647 , ..., -0.37616 , -0.032502,
         0.8062  ],
       [-0.49886 ,  0.76602 ,  0.89751 , ..., -0.41179 ,  0.40539 ,
         0.78504 ],
       ...,
       [-0.46263 ,  0.069864,  0.69095 , ..., -0.29174 ,  0.32041 ,
         0.21202 ],
       [ 0.073242,  0.11134 ,  0.62281 , ...,  0.53417 , -0.1646  ,
        -0.27516 ],
       [ 0.29019 ,  0.80497 ,  0.31187 , ..., -0.33603 ,  0.45998 ,
        -0.11278 ]])

In [109]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN, Embedding

In [110]:
model = Sequential(
    [Embedding(input_dim = len(w2i)+1,
               output_dim = embed_s,
               input_length = max_len,
               weights = [e_matrix]),

     LSTM(units = 16, return_sequences = True),
      LSTM(units=4),
      Dense(5, activation = 'sigmoid')
    ]
)

C:\Users\MOHIT MAURYA\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [111]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [112]:
y

['4',
 '3',
 '3 ',
 '1 ',
 '2',
 '1',
 '4',
 '3',
 '4',
 '1',
 '3',
 '3 ',
 '2',
 '2',
 '4',
 '3',
 '2',
 '3 ',
 '3 ',
 '1',
 '3 ',
 '2',
 '2',
 '2',
 '0',
 '1',
 '0',
 '4 ',
 '2',
 '0',
 '2',
 '0',
 '0',
 '3 ',
 '4',
 '0',
 '2',
 '1',
 '3',
 '1',
 '0',
 '4',
 '0 ',
 '3',
 '0 ',
 '4',
 '2',
 '3 ',
 '4',
 '2 ',
 '2',
 '3',
 '0',
 '2',
 '2',
 '3 ',
 '2',
 '3',
 '2',
 '2',
 '3 ',
 '3',
 '0 ',
 '2',
 '3',
 '0',
 '2',
 '0',
 '0 ',
 '2',
 '3',
 '2',
 '4',
 '1',
 '3',
 '3',
 '0',
 '0',
 '3',
 '2',
 '0',
 '3',
 '0',
 '2',
 '2',
 '4',
 '2',
 '2',
 '0',
 '0',
 '2',
 '3',
 '0',
 '4',
 '2',
 '1',
 '2',
 '3',
 '3',
 '2',
 '3',
 '0',
 '3',
 '0',
 '2',
 '0',
 '2',
 '3',
 '4',
 '3',
 '1',
 '3',
 '4',
 '3',
 '2',
 '3',
 '3',
 '3',
 '1',
 '4',
 '4',
 '2',
 '2',
 '1',
 '1',
 '2',
 '3',
 '2',
 '3',
 '4',
 '2',
 '3',
 '0',
 '2',
 '0',
 '0',
 '4',
 '3',
 '4',
 '2',
 '3',
 '2',
 '3',
 '4',
 '2',
 '1',
 '2',
 '4',
 '3',
 '1',
 '3',
 '2',
 '3',
 '2',
 '2',
 '3',
 '3',
 '2',
 '4',
 '0',
 '0',
 '0',
 '3',
 '0',


In [113]:
ytrain = to_categorical(y)

In [114]:
ytrain

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0.

In [162]:
model.fit(xtrain, ytrain, epochs =100)

Epoch 1/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8555 - loss: 0.8680 
Epoch 2/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8293 - loss: 0.8340 
Epoch 3/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8738 - loss: 0.7851 
Epoch 4/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8665 - loss: 0.7748 
Epoch 5/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8729 - loss: 0.7485 
Epoch 6/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8607 - loss: 0.7335 
Epoch 7/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8689 - loss: 0.7105 
Epoch 8/100
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8866 - loss: 0.6818 
Epoch 9/

In [163]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)              │ (None, 10, 100)             │          31,300 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_7 (LSTM)                        │ (None, 10, 16)              │           7,488 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_8 (LSTM)                        │ (None, 4)                   │             336 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 5)                   │              25 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 117,449 (458.79 KB)

 Trainable params: 39,149 (152.93 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 78,300 (305.86 KB)

In [164]:
test = ['i am hungry', 'playing', 'in love', 'valentine week']
test_s = tokenizer.texts_to_sequences(test)
xtest = pad_sequences(test_s, maxlen = max_len, padding = 'post')

y_pred = model.predict(xtest)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


In [165]:
y_pred

array([[0.65213466, 0.19382018, 0.05676575, 0.05276209, 0.87009007],
       [0.30995473, 0.23296289, 0.9685071 , 0.5987288 , 0.15170877],
       [0.93454516, 0.16634475, 0.4474743 , 0.02308286, 0.6923219 ],
       [0.94261366, 0.15658224, 0.41553998, 0.02021814, 0.72077215]],
      dtype=float32)

In [166]:
y_pred = np.argmax(y_pred, axis = 1)

In [167]:
y_pred

array([4, 2, 0, 0], dtype=int64)

In [168]:
to_emoji(y_pred[2])

'❤️'

In [169]:
test = ["i am good", "i am bad", "eat lunch", "baseball afternoon"]

In [170]:
test_s = tokenizer.texts_to_sequences(test)

In [171]:
xtest = pad_sequences(test_s, maxlen = max_len, padding = 'post')

In [172]:
y_pred = model.predict(xtest)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


In [173]:
y_pred = np.argmax(y_pred, axis = 1)

In [174]:
y_pred

array([2, 3, 4, 1], dtype=int64)

In [175]:
for z in range(len(test)):
    print(test[z], to_emoji(y_pred[z]))

i am good :beaming_face_with_smiling_:
i am bad üòî
eat lunch üòã
baseball afternoon üèè
